version: "3.9"

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - apinode
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'apiNode'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
    volumes:
      - mysql-data:/var/lib/mysql      
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - apinode
networks:
  apinode:
    driver: bridge
volumes:
  mysql-data:
      driver: local
